In [2]:
import pandas as pd # for csv files read or export
import numpy as nm # for math
from sklearn import linear_model # for learn model

In [8]:
df=pd.read_csv("homeprices2.csv")# relatively saved & display DATA FRAME
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
import math
df.bedrooms.median()# median math fuction call for find median in bedroom 

4.0

In [24]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median()) # fil NAN Not A Number = math median & fillna is pandas method
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [34]:
model=linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price) # fit method train to model by
#  passing 2 parameter 1)only dependedent & here DATA FRAME drop price  2) independent
# model is fully train here

LinearRegression()

In [37]:
model.predict([[3000,3,40]]) # it predict price using dependent variable I am share 3 in csv 
# 1) area 2) bedrooms 3) age & it return price predict

array([498408.25158031])

In [39]:
model.coef_ # three value 1) area 2)bedrooms 3) age {age negative becuse it decrese value of price}

array([  112.06244194, 23388.88007794, -3231.71790863])

In [41]:
model.intercept_# because one common

221323.00186540425

In [45]:
# formula used for predict price=m1*area + m2*bedrooms + m3*age + intercept
#  m is coeffiecient 
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540425
# output same as predict

498408.25157402427

In [47]:
model.predict([[2500,4,5]])# 2500 sqr ft 4 bedrooms 5 year old age

array([578876.03748933])