In [1]:
import pandas as pd # for reading file 
import numpy as np # for math
from sklearn import linear_model# for model Learning 

In [9]:
df = pd.read_csv("homeprices.csv") # reading csv file
df.head() # i dont know why head used.

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [10]:
model = linear_model.LinearRegression() # model
model.fit(df[['area']],df.price)# train model by providing dependent and independent value

LinearRegression()

In [11]:
model.coef_

array([135.78767123])

In [12]:
model.intercept_

180616.43835616432

In [13]:
model.predict([[5000]])

array([859554.79452055])

In [16]:
import pickle # pickle is used for save model or things...

In [15]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)# save done
#here with open is opening file and permission is wb ==> write 
#  pickle.dump is save model
#


In [17]:
# open saved model
with open('model_pickle','rb') as f:
    my_local_model=pickle.load(f)

In [21]:
mp=my_local_model
mp.coef_# coeffficient

array([135.78767123])

In [22]:
mp.intercept_

180616.43835616432

In [23]:
mp.predict([[5000]])

array([859554.79452055])